# Generated by Django 3.2.5 on 2021-11-17 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('className', models.CharField(max_length=100)),
                ('courseID', models.CharField(max_length=50)),
                ('description', models.TextField(default=None)),
                ('teacher', models.EmailField(max_length=100)),
                ('classTeacherMail', models.CharField(max_length=254, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherClassroom',
            fields=[
                ('teacherEmail', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('classTeacherMail', models.ManyToManyField(to='classRoom.Classroom')),
            ],
        ),
        migrations.CreateModel(
            name='StudentClassroom',
            fields=[
                ('studentEmail', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('classTeacherMail', models.ManyToManyField(to='classRoom.Classroom')),
            ],
        ),
    ]
