# Generated by Django 3.2.5 on 2021-11-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classRoom', '0002_alter_classroom_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='classCode',
            field=models.CharField(default='123abc', max_length=10),
            preserve_default=False,
        ),
    ]
