# Generated by Django 3.2.5 on 2021-11-18 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classRoom', '0003_classroom_classcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='description',
        ),
    ]
